reload("user.options")
reload("user.keymaps")
reload("user.plugins")
reload("user.lsp")
reload("user.treesitter")
reload("user.autopairs")
reload("user.comment")
reload("user.nvim-tree")
reload("user.toggleterm")
-- reload("user.project")
reload("user.impatient")
reload("user.indentline")
reload("user.autocommands")
reload("user.zenmode")
reload("user.whichkey")
reload("user.neogit")
reload("user.git")
