#! /usr/bin/env bash
export XDG_CONFIG_HOME=${HOME}/.config
export XDG_CACHE_HOME=${HOME}/.cache
export XDG_DATA_HOME=${HOME}/.local/share
export XDG_RUNTIME_DIR=${HOME}/tmp/xdg_runtime

while read -r env; do
  echo "Sourcing $env"
  source "${env}"
done < <(find . -name env.zsh)
echo ''

echo "Setting PATH..."
echo ''

source zsh/path.zsh

echo "Setting up Homebrew..."
echo ''

UNAME=`uname`
if test ! "$(command -v brew)"; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  
  if [ "$UNAME" = "Linux" ]; then
    echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> ${XDG_CONFIG_HOME}/zsh/local.zsh
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

    sudo apt-get install build-essential
    brew install gcc
    brew bundle --file=Brewfile.linux

  else if [ "$UNAME" == "Darwin" ]; then
    brew bundle --file=Brewfile.darwin
  fi
else
  while read -r brw; do
    echo "${brw}"
  done < <(brew update)
  echo ''
fi

source "$XDG_CONFIG_HOME/zsh/.zshrc"