
################################################################################
# Tap 
################################################################################
tap 'mongodb/brew'
tap 'homebrew/cask'
tap 'homebrew/cask-drivers'
tap 'homebrew/cask-fonts'
tap 'homebrew/services'
tap 'getantibody/tap'


################################################################################
# Simple brews
################################################################################
brew 'getantibody/tap/antibody'
brew 'ack'
brew 'asciinema'
brew 'bat'
brew 'ctags'
brew 'exa'
brew 'fzf'
brew 'fd'
brew 'git'
brew 'grep'
brew 'gzip'
brew 'go'
brew 'httpie'
brew 'jq'
brew 'kubernetes-cli'
brew 'kubernetes-helm'
brew 'lua@5.1'
brew 'luarocks'
brew 'make'
brew 'mariadb'
brew 'mongodb-community'
brew 'nats-server'
brew 'nmap'
brew 'neovim'
brew 'openssl'
brew 'postgresql'
brew 'postgis'
brew 'python'
brew 'rpm'
brew 'ruby'
brew 'ripgrep'
brew 'shellcheck'
brew 'telnet'
brew 'tig'
brew 'tldr'
brew 'tmux'
brew 'tree'
brew 'utf8proc'
brew 'vault'
brew 'vim'
brew 'watch'
brew 'wdiff'
brew 'wget'
brew 'weechat'
brew 'xz'
brew 'yarn'
brew 'yq'
brew 'zsh'
brew 'prettier'
brew 'node'

