################################################################################
# Simple brews
################################################################################
brew 'ack'
brew 'asciinema'
brew 'ctags'
brew 'fzf'
brew 'git'
brew 'grep'
brew 'gzip'
brew 'go'
brew 'httpie'
brew 'jq'
brew 'kubernetes-cli'
brew 'lua@5.1'
brew 'luarocks'
brew 'make'
brew 'mariadb'
brew 'mongodb-community@4.2'
brew 'nats-streaming-server'
brew 'nmap'
brew 'nvm'
brew 'openssl'
brew 'postgresql', restart_service: :changed
brew 'postgis'
brew 'prettier'
brew 'python'
brew 'python@2'
brew 'python@3'
brew 'rpm'
brew 'ruby'
brew 'shellcheck'
brew 'telnet'
brew 'tig'
brew 'tldr'
brew 'tmux'
brew 'tree'
brew 'utf8proc'
brew 'vault'
brew 'vim'
brew 'watch'
brew 'wdiff'
brew 'wget'
brew 'xz'
brew 'yarn'
brew 'yq'
brew 'zsh'