#!/bin/bash

echo "RUNNING FULL INSTALL"
set -x

make all

export XDG_CONFIG_HOME="$HOME/.config"

mkdir -p "$XDG_CONFIG_HOME"/nixpkgs

ln -sf "$PWD/nix/config.nix" "$XDG_CONFIG_HOME"/nixpkgs/config.nix

nix-env -iA nixpkgs.myPackages
