#! /usr/bin/env bash

export XDG_CONFIG_HOME=${HOME}/.config
export XDG_CACHE_HOME=${HOME}/.cache
export XDG_DATA_HOME=${HOME}/.local/share
export XDG_RUNTIME_DIR=${HOME}/tmp/xdg_runtime

mkdir -p $(XDG_CONFIG_HOME)
mkdir -p $(XDG_CACHE_HOME)
mkdir -p $(XDG_DATA_HOME)
mkdir -p $(XDG_RUNTIME_DIR)

ln -sf "$PWD/nvim" "$XDG_CONFIG_HOME"/nvim

# install Nix packages from config.nix
mkdir -p $(XDG_CONFIG_HOME)/nixpkgs
nix-env -iA nixpkgs.myPackages
