return {
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "black",
        "codelldb",
        "eslint-lsp",
        "gofumpt",
        "goimports",
        "gopls",
        "json-lsp",
        "lua-language-server",
        "flake8",
        "markdownlint",
        "marksman",
        "prettier",
        "rust-analyzer",
        "shfmt",
        "shellcheck",
        "staticcheck",
        "stylua",
        "taplo",
        "terraform-ls",
        "typescript-language-server",
        "yaml-language-server",
      },
    },
  },
}
