palette = "catppuccin_frappe"

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = 'bold blue'
symbol = "  "

[character]
success_symbol = "[❯](teal)"
error_symbol = "[❯](maroon)"
vimcmd_symbol = "[❮](green)"

[directory]
truncation_length = 3
truncate_to_repo = false
read_only = " "
style = "bold subtext0"

[docker_context]
disabled = true

[git_branch]
symbol = " "
style = "bold rosewater"
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_status]
format = "[$ahead_behind$untracked$modified]($style) "

[golang]
format = '[($version )($mod_version )]($style)'

[kubernetes]
symbol = '☸ '
disabled = false
detect_files = ['Dockerfile']
format = '[$context(\[$namespace\])]($style) '

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[rust]
format = '[symbol(version )](style)'

[terraform]
format = "[$symbol$workspace]($style)"

[username]
format = "[$user]($style)@"
