export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
# export XDG_RUNTIME_DIR=/run/user/$UID
case "$(uname -s)" in
  Darwin)
    export XDG_RUNTIME_DIR="$TMPDIR"
    ;;
  Linux)
    export XDG_RUNTIME_DIR="/run/user/$(id -u)"
    ;;
esac
export SHELL="/bin/zsh"
export ZSH_THEME=""
export ZDOTDIR=$XDG_CONFIG_HOME/zsh/
export ZSH_CACHE_DIR=$XDG_CACHE_HOME/zsh/
export ZSH_COMPLETIONS_DIR=$XDG_CACHE_HOME/zsh/completions
