export XDG_CONFIG_HOME=${HOME}/.config
export XDG_CACHE_HOME=${HOME}/.cache
export XDG_DATA_HOME=${HOME}/.local/share
export XDG_RUNTIME_DIR=${HOME}/tmp/runtime

# Path to your oh-my-zsh installation.
export ZSH=/Users/$USER/.oh-my-zsh
export ZSH_THEME=""
export UPDATE_ZSH_DAYS=13
export ZDOTDIR=${XDG_CONFIG_HOME}/zsh
export ZSH_COMPDUMP=${XDG_CACHE_HOME}/zsh

# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
export HIST_STAMPS="mm/dd/yyyy"
export HISTFILE="${XDG_DATA_HOME}"/zsh/history
export HISTSIZE=10000
export SAVEHIST=${HISTSIZE}

